version: '3.8'
services:
  db:
    image: mysql:8.0
    # cap_add:
    #  - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=angular_springboot_demo
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  # angular:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4201:80"
  #   container_name: angular-springboot-demo-frontend
  # java:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   container_name: angular-springboot-demo-backend

volumes:
  db:
    driver: local
